import { romanCandidateToChord, type KeyMode } from "./chordRecommendations";

export type PresetMode = "major" | "minor" | "either";

export type ProgressionPresetCategory =
  | "I-start"
  | "IV-start"
  | "vi-start"
  | "minor"
  | "ii-V"
  | "turnaround"
  | "modal"
  | "borrowed"
  | "other";

export type ProgressionUseCase =
  | "intro"
  | "verse"
  | "pre-chorus"
  | "chorus"
  | "bridge"
  | "ending"
  | "loop"
  | "turnaround"
  | "drop";

export type ReferenceSong = {
  title: string;
  artist?: string;
  section?:
    | "intro"
    | "verse"
    | "pre-chorus"
    | "chorus"
    | "bridge"
    | "outro"
    | "unknown";
  confidence: "high" | "medium" | "low";
  note?: string;
};

export type ProgressionPreset = {
  id: string;
  name: string;
  roman: string[];
  mode: PresetMode;
  category: ProgressionPresetCategory;
  genres: string[];
  moods: string[];
  useCases: ProgressionUseCase[];
  complexity: 1 | 2 | 3 | 4 | 5;
  description: string;
  vibeExamples?: string[];
  referenceSongs?: ReferenceSong[];
  commonUse?: string;
  variationHints?: string[];
};

export type StarterProgressionPreset = ProgressionPreset;

export type PresetFilter = {
  category?: string;
  genre?: string;
  mood?: string;
  useCase?: string;
  complexity?: string;
  search?: string;
};

type PresetBuildInput = {
  id: string;
  name: string;
  roman: string[];
  mode: PresetMode;
  category: ProgressionPresetCategory;
  genres: string[];
  moods: string[];
  useCases: ProgressionUseCase[];
  complexity: 1 | 2 | 3 | 4 | 5;
  description: string;
  vibeExamples?: string[];
  variationHints?: string[];
};

const PRESET_CHORD_CACHE_LIMIT = 512;
const presetChordCache = new Map<string, string[]>();

function preset(input: PresetBuildInput): ProgressionPreset {
  return input;
}

export const PRESET_CATEGORY_LABELS: Record<ProgressionPresetCategory, string> = {
  "I-start": "I-start",
  "IV-start": "IV-start",
  "vi-start": "vi-start",
  minor: "Minor",
  "ii-V": "ii-V / Jazz",
  turnaround: "Turnaround",
  modal: "Modal",
  borrowed: "Borrowed",
  other: "Other",
};

export const STARTER_PRESETS: ProgressionPreset[] = [
  preset({
    id: "axis",
    name: "Axis Progression",
    roman: ["I", "V", "vi", "IV"],
    mode: "major",
    category: "I-start",
    genres: ["Pop", "Rock", "J-Pop"],
    moods: ["bright", "emotional", "loopable"],
    useCases: ["chorus", "loop"],
    complexity: 1,
    description: "Universal four-chord pop seed with an easy chorus lift.",
    vibeExamples: ["big pop chorus", "anime ending", "radio rock hook"],
  }),
  preset({
    id: "fifties",
    name: "50s Progression",
    roman: ["I", "vi", "IV", "V"],
    mode: "major",
    category: "I-start",
    genres: ["Pop", "Rock", "Ballad"],
    moods: ["nostalgic", "stable", "bright"],
    useCases: ["verse", "chorus", "turnaround"],
    complexity: 1,
    description: "Classic tonic-to-relative-minor loop with a clean V return.",
    vibeExamples: ["oldies ballad", "retro pop refrain"],
  }),
  preset({
    id: "folk-basic",
    name: "Folk Basic",
    roman: ["I", "IV", "V", "I"],
    mode: "major",
    category: "I-start",
    genres: ["Pop", "Rock", "Ballad"],
    moods: ["stable", "bright", "loopable"],
    useCases: ["verse", "chorus", "loop"],
    complexity: 1,
    description: "Plain tonic, subdominant, dominant motion that stays grounded.",
  }),
  preset({
    id: "soft-ballad",
    name: "Soft Ballad",
    roman: ["I", "iii", "IV", "V"],
    mode: "major",
    category: "I-start",
    genres: ["J-Pop", "Pop", "Ballad"],
    moods: ["emotional", "nostalgic", "stable"],
    useCases: ["verse", "pre-chorus"],
    complexity: 2,
    description: "Gentle mediant color into a familiar IV-V lift.",
  }),
  preset({
    id: "rocking-home",
    name: "Rocking Home",
    roman: ["I", "V", "IV", "I"],
    mode: "major",
    category: "I-start",
    genres: ["Rock", "Pop"],
    moods: ["bright", "stable", "loopable"],
    useCases: ["verse", "loop"],
    complexity: 1,
    description: "Back-and-forth rock motion with a clear plagal return.",
  }),
  preset({
    id: "stadium-rock",
    name: "Stadium Rock",
    roman: ["I", "IV", "vi", "V"],
    mode: "major",
    category: "I-start",
    genres: ["Rock", "Pop"],
    moods: ["bright", "dramatic", "loopable"],
    useCases: ["chorus", "bridge"],
    complexity: 2,
    description: "Broad IV lift, relative minor color, and a strong V ending.",
  }),
  preset({
    id: "major-turnaround-loop",
    name: "Major Turnaround Loop",
    roman: ["Imaj7", "vi7", "ii7", "V7"],
    mode: "major",
    category: "I-start",
    genres: ["City Pop", "Jazz", "R&B"],
    moods: ["smooth", "nostalgic", "loopable"],
    useCases: ["intro", "verse", "turnaround"],
    complexity: 3,
    description: "A polished tonic-to-cadence loop for city pop and R&B.",
    vibeExamples: ["city night intro", "smooth verse vamp"],
  }),
  preset({
    id: "tonic-climb",
    name: "Tonic Climb",
    roman: ["I", "ii", "iii", "IV"],
    mode: "major",
    category: "I-start",
    genres: ["Pop", "Game", "J-Pop"],
    moods: ["bright", "floating", "stable"],
    useCases: ["intro", "pre-chorus"],
    complexity: 2,
    description: "Stepwise lift away from I into a clear IV arrival.",
  }),
  preset({
    id: "country-loop",
    name: "Country Loop",
    roman: ["I", "V", "I", "IV"],
    mode: "major",
    category: "I-start",
    genres: ["Pop", "Rock"],
    moods: ["stable", "bright", "loopable"],
    useCases: ["verse", "loop"],
    complexity: 1,
    description: "Simple I-V-I-IV shape that leaves space for melody.",
  }),
  preset({
    id: "doowop-seven",
    name: "Doowop 7th",
    roman: ["Imaj7", "vi7", "IVmaj7", "V7"],
    mode: "major",
    category: "I-start",
    genres: ["Pop", "R&B", "City Pop"],
    moods: ["nostalgic", "smooth", "emotional"],
    useCases: ["verse", "chorus"],
    complexity: 3,
    description: "Old-school motion with smoother seventh-chord color.",
  }),
  preset({
    id: "bright-cycle",
    name: "Bright Cycle",
    roman: ["I", "V", "ii", "IV"],
    mode: "major",
    category: "I-start",
    genres: ["Pop", "Game", "EDM"],
    moods: ["bright", "floating", "loopable"],
    useCases: ["intro", "loop"],
    complexity: 2,
    description: "Open tonic and dominant colors before a soft IV landing.",
  }),
  preset({
    id: "open-pop",
    name: "Open Pop",
    roman: ["I", "IV", "I", "V"],
    mode: "major",
    category: "I-start",
    genres: ["Pop", "Ballad"],
    moods: ["stable", "bright", "emotional"],
    useCases: ["verse", "chorus"],
    complexity: 1,
    description: "Direct and singable I-IV-I-V movement.",
  }),
  preset({
    id: "lyric-lift",
    name: "Lyric Lift",
    roman: ["I", "iii", "vi", "IV"],
    mode: "major",
    category: "I-start",
    genres: ["J-Pop", "Pop", "Ballad"],
    moods: ["emotional", "floating", "nostalgic"],
    useCases: ["verse", "pre-chorus"],
    complexity: 2,
    description: "Tonic-area drift into a softer subdominant landing.",
  }),
  preset({
    id: "pop-prep",
    name: "Pop Prep",
    roman: ["I", "ii7", "IV", "V"],
    mode: "major",
    category: "I-start",
    genres: ["Pop", "J-Pop"],
    moods: ["bright", "stable", "dramatic"],
    useCases: ["pre-chorus", "chorus"],
    complexity: 2,
    description: "Tonic into predominant colors that set up a chorus.",
  }),
  preset({
    id: "resolved-pop",
    name: "Resolved Pop",
    roman: ["I", "vi", "ii", "V"],
    mode: "major",
    category: "I-start",
    genres: ["Pop", "Ballad", "Jazz"],
    moods: ["nostalgic", "smooth", "stable"],
    useCases: ["verse", "turnaround"],
    complexity: 2,
    description: "Circle-like motion from I through vi and ii to V.",
  }),
  preset({
    id: "major-home-run",
    name: "Major Home Run",
    roman: ["I", "V7", "vi", "IV"],
    mode: "major",
    category: "I-start",
    genres: ["Pop", "J-Pop", "Rock"],
    moods: ["emotional", "bright", "loopable"],
    useCases: ["chorus", "loop"],
    complexity: 2,
    description: "A sharper dominant color before the relative minor landing.",
  }),
  preset({
    id: "royal-road",
    name: "Royal Road",
    roman: ["IV", "V", "iii", "vi"],
    mode: "major",
    category: "IV-start",
    genres: ["J-Pop", "Anime", "Game"],
    moods: ["emotional", "dramatic", "loopable"],
    useCases: ["chorus", "pre-chorus", "loop"],
    complexity: 2,
    description: "J-Pop staple with a bright lift into relative minor.",
    vibeExamples: ["anime chorus lift", "idol-pop refrain", "game theme hook"],
    variationHints: ["Insert V/vi before vi", "Extend with ii7 V7 Imaj7"],
  }),
  preset({
    id: "anime-pre",
    name: "Anime Pre",
    roman: ["IV", "V", "I", "I"],
    mode: "major",
    category: "IV-start",
    genres: ["J-Pop", "Anime"],
    moods: ["bright", "dramatic", "stable"],
    useCases: ["pre-chorus", "chorus"],
    complexity: 1,
    description: "Direct IV-V lift into an open tonic hold.",
  }),
  preset({
    id: "jpop-float",
    name: "J-Pop Float",
    roman: ["IVmaj7", "V7", "iii7", "vi7"],
    mode: "major",
    category: "IV-start",
    genres: ["J-Pop", "Anime", "City Pop"],
    moods: ["floating", "emotional", "smooth"],
    useCases: ["verse", "pre-chorus", "loop"],
    complexity: 3,
    description: "Soft major-seventh color with a bittersweet minor landing.",
  }),
  preset({
    id: "four-to-one-pop",
    name: "IV to I Pop",
    roman: ["IV", "I", "V", "vi"],
    mode: "major",
    category: "IV-start",
    genres: ["Pop", "J-Pop"],
    moods: ["bright", "emotional", "loopable"],
    useCases: ["chorus", "loop"],
    complexity: 2,
    description: "Starts with lift, then circles through I and V into vi.",
  }),
  preset({
    id: "four-five-six-one",
    name: "Lift to vi",
    roman: ["IV", "V", "vi", "I"],
    mode: "major",
    category: "IV-start",
    genres: ["Pop", "J-Pop", "EDM"],
    moods: ["emotional", "bright", "loopable"],
    useCases: ["chorus", "loop"],
    complexity: 2,
    description: "A clean IV-V push that lands on vi before resetting.",
  }),
  preset({
    id: "descending-predominant",
    name: "Descending Predominant",
    roman: ["IV", "iii", "ii", "I"],
    mode: "major",
    category: "IV-start",
    genres: ["J-Pop", "Ballad", "Game"],
    moods: ["nostalgic", "smooth", "emotional"],
    useCases: ["verse", "ending"],
    complexity: 3,
    description: "Stepwise descent from IV back into tonic.",
  }),
  preset({
    id: "royal-secondary",
    name: "Royal Secondary",
    roman: ["IV", "V", "V/vi", "vi"],
    mode: "major",
    category: "IV-start",
    genres: ["J-Pop", "Anime"],
    moods: ["dramatic", "emotional", "tense"],
    useCases: ["pre-chorus", "chorus"],
    complexity: 3,
    description: "Royal-road lift with a secondary dominant into vi.",
  }),
  preset({
    id: "minor-plagal-tag",
    name: "Minor Plagal Tag",
    roman: ["IV", "iv", "I"],
    mode: "major",
    category: "IV-start",
    genres: ["R&B", "Ballad", "J-Pop"],
    moods: ["emotional", "smooth", "nostalgic"],
    useCases: ["ending", "bridge"],
    complexity: 2,
    description: "IV softens into borrowed iv before resolving home.",
  }),
  preset({
    id: "city-pop-iv",
    name: "City Pop IV",
    roman: ["IVmaj7", "III7", "vi7", "V7"],
    mode: "major",
    category: "IV-start",
    genres: ["City Pop", "J-Pop", "R&B"],
    moods: ["smooth", "floating", "nostalgic"],
    useCases: ["intro", "verse", "loop"],
    complexity: 4,
    description: "Glossy IV color with a secondary-dominant pull to vi.",
  }),
  preset({
    id: "hopeful-iv",
    name: "Hopeful IV",
    roman: ["IV", "I", "ii7", "V"],
    mode: "major",
    category: "IV-start",
    genres: ["Pop", "Ballad", "J-Pop"],
    moods: ["bright", "emotional", "stable"],
    useCases: ["verse", "pre-chorus"],
    complexity: 2,
    description: "Plagal start that turns into a functional cadence.",
  }),
  preset({
    id: "soft-launch",
    name: "Soft Launch",
    roman: ["IVmaj7", "Imaj7", "iii7", "vi7"],
    mode: "major",
    category: "IV-start",
    genres: ["R&B", "City Pop", "Ballad"],
    moods: ["smooth", "floating", "emotional"],
    useCases: ["intro", "verse"],
    complexity: 3,
    description: "Airy IV-to-I color drifting through tonic-area chords.",
  }),
  preset({
    id: "iv-backdoor-pop",
    name: "Backdoor Prep",
    roman: ["IV", "iv7", "bVII7", "Imaj7"],
    mode: "major",
    category: "IV-start",
    genres: ["Jazz", "R&B", "City Pop"],
    moods: ["smooth", "nostalgic", "emotional"],
    useCases: ["bridge", "ending"],
    complexity: 4,
    description: "IV opens into borrowed minor and a backdoor cadence.",
  }),
  preset({
    id: "pre-chorus-ramp",
    name: "Pre-Chorus Ramp",
    roman: ["IV", "V", "vi", "V"],
    mode: "major",
    category: "IV-start",
    genres: ["J-Pop", "Anime", "Pop"],
    moods: ["dramatic", "tense", "emotional"],
    useCases: ["pre-chorus"],
    complexity: 2,
    description: "Lift, release, and hold dominant tension for the hook.",
  }),
  preset({
    id: "lydian-open",
    name: "Lydian Open",
    roman: ["IVmaj7", "V", "I", "II"],
    mode: "major",
    category: "IV-start",
    genres: ["Game", "Pop", "Anime"],
    moods: ["bright", "floating", "dramatic"],
    useCases: ["intro", "bridge"],
    complexity: 3,
    description: "Open IV color with a raised-II sparkle at the end.",
  }),
  preset({
    id: "komuro",
    name: "Komuro",
    roman: ["vi", "IV", "V", "I"],
    mode: "major",
    category: "vi-start",
    genres: ["J-Pop", "Pop"],
    moods: ["emotional", "bright", "loopable"],
    useCases: ["chorus", "loop"],
    complexity: 2,
    description: "Relative-minor start moving through IV and V to major tonic.",
    vibeExamples: ["90s J-Pop chorus", "anime pop refrain"],
    variationHints: ["Insert ii7 before V", "Add V/vi when looping"],
  }),
  preset({
    id: "emotional-lift",
    name: "Emotional Lift",
    roman: ["vi", "IV", "I", "V"],
    mode: "major",
    category: "vi-start",
    genres: ["J-Pop", "Pop", "Rock"],
    moods: ["emotional", "bright", "loopable"],
    useCases: ["chorus", "loop"],
    complexity: 1,
    description: "A familiar emotional loop that keeps momentum open.",
  }),
  preset({
    id: "sad-pop",
    name: "Sad Pop",
    roman: ["vi", "IV", "I", "V"],
    mode: "major",
    category: "vi-start",
    genres: ["Pop", "J-Pop", "Ballad"],
    moods: ["emotional", "nostalgic", "loopable"],
    useCases: ["verse", "chorus"],
    complexity: 1,
    description: "Relative-minor first version of a bright pop cycle.",
  }),
  preset({
    id: "bittersweet",
    name: "Bittersweet",
    roman: ["vi", "iii", "IV", "I"],
    mode: "major",
    category: "vi-start",
    genres: ["Pop", "J-Pop", "Ballad"],
    moods: ["emotional", "nostalgic", "smooth"],
    useCases: ["verse", "bridge"],
    complexity: 2,
    description: "Gentle minor-mediant path into IV and I.",
  }),
  preset({
    id: "circle-motion",
    name: "Circle Motion",
    roman: ["vi", "ii", "V", "I"],
    mode: "major",
    category: "vi-start",
    genres: ["Jazz", "City Pop", "Pop"],
    moods: ["smooth", "stable", "resolved"],
    useCases: ["turnaround", "ending"],
    complexity: 2,
    description: "Circle progression from vi through a full cadence.",
  }),
  preset({
    id: "minor-feel-pop",
    name: "Minor-Feel Pop",
    roman: ["vi", "V", "IV", "V"],
    mode: "major",
    category: "vi-start",
    genres: ["J-Pop", "Anime", "Pop"],
    moods: ["tense", "emotional", "dramatic"],
    useCases: ["pre-chorus", "loop"],
    complexity: 2,
    description: "Minor start with repeated dominant pressure.",
  }),
  preset({
    id: "minor-feel-return",
    name: "Minor-Feel Return",
    roman: ["vi", "V", "IV", "I"],
    mode: "major",
    category: "vi-start",
    genres: ["Pop", "J-Pop"],
    moods: ["emotional", "stable", "nostalgic"],
    useCases: ["verse", "chorus"],
    complexity: 2,
    description: "Relative-minor opening that resolves to major tonic.",
  }),
  preset({
    id: "minor-color-lift",
    name: "Minor Color Lift",
    roman: ["vi", "bVII", "I", "V"],
    mode: "major",
    category: "vi-start",
    genres: ["Rock", "Anime", "Game"],
    moods: ["dramatic", "bright", "tense"],
    useCases: ["bridge", "chorus"],
    complexity: 3,
    description: "Modal bVII lifts the relative-minor start into I.",
  }),
  preset({
    id: "sad-cycle",
    name: "Sad Cycle",
    roman: ["vi", "IV", "ii", "V"],
    mode: "major",
    category: "vi-start",
    genres: ["Ballad", "J-Pop", "Pop"],
    moods: ["emotional", "smooth", "resolved"],
    useCases: ["verse", "turnaround"],
    complexity: 2,
    description: "Minor start that turns into a classic predominant cadence.",
  }),
  preset({
    id: "vi-city",
    name: "vi City",
    roman: ["vi7", "IVmaj7", "ii7", "V7"],
    mode: "major",
    category: "vi-start",
    genres: ["City Pop", "R&B", "J-Pop"],
    moods: ["smooth", "nostalgic", "floating"],
    useCases: ["verse", "loop"],
    complexity: 3,
    description: "Relative-minor seventh color with a city-pop cadence tail.",
  }),
  preset({
    id: "vi-dream",
    name: "vi Dream",
    roman: ["vi7", "Imaj7", "IVmaj7", "V7"],
    mode: "major",
    category: "vi-start",
    genres: ["R&B", "Pop", "Ballad"],
    moods: ["floating", "smooth", "emotional"],
    useCases: ["intro", "verse"],
    complexity: 3,
    description: "Dreamy relative-minor color that still points to V.",
  }),
  preset({
    id: "vi-royal",
    name: "vi Royal",
    roman: ["vi", "IV", "V", "iii"],
    mode: "major",
    category: "vi-start",
    genres: ["J-Pop", "Anime"],
    moods: ["emotional", "loopable", "dramatic"],
    useCases: ["loop", "pre-chorus"],
    complexity: 2,
    description: "Komuro-like opening that delays the vi resolution.",
  }),
  preset({
    id: "minor-reset",
    name: "Minor Reset",
    roman: ["vi", "V/vi", "vi", "IV"],
    mode: "major",
    category: "vi-start",
    genres: ["J-Pop", "Anime", "Game"],
    moods: ["tense", "emotional", "loopable"],
    useCases: ["loop", "bridge"],
    complexity: 3,
    description: "Secondary dominant keeps pulling back into vi.",
  }),
  preset({
    id: "aeolian-loop",
    name: "Aeolian Loop",
    roman: ["i", "bVI", "bVII", "i"],
    mode: "minor",
    category: "minor",
    genres: ["Rock", "Pop", "Game"],
    moods: ["dark", "stable", "loopable"],
    useCases: ["loop", "verse"],
    complexity: 1,
    description: "Natural-minor loop with a clear modal return.",
  }),
  preset({
    id: "andalusian",
    name: "Andalusian",
    roman: ["i", "bVII", "bVI", "V"],
    mode: "minor",
    category: "minor",
    genres: ["Rock", "Game", "Ballad"],
    moods: ["dark", "dramatic", "tense"],
    useCases: ["verse", "bridge"],
    complexity: 2,
    description: "Dramatic minor descent with harmonic-minor dominant.",
  }),
  preset({
    id: "minor-epic",
    name: "Minor Epic",
    roman: ["i", "bVI", "bIII", "bVII"],
    mode: "minor",
    category: "minor",
    genres: ["Game", "Rock", "EDM"],
    moods: ["dark", "dramatic", "loopable"],
    useCases: ["intro", "chorus", "loop"],
    complexity: 2,
    description: "Wide natural-minor motion with cinematic weight.",
  }),
  preset({
    id: "dark-loop",
    name: "Dark Loop",
    roman: ["i", "bVI", "iv", "V"],
    mode: "minor",
    category: "minor",
    genres: ["Rock", "Game", "Anime"],
    moods: ["dark", "tense", "dramatic"],
    useCases: ["verse", "loop"],
    complexity: 2,
    description: "Minor color that tightens into a harmonic dominant.",
  }),
  preset({
    id: "harmonic-minor",
    name: "Harmonic Minor",
    roman: ["i", "iv", "V", "i"],
    mode: "minor",
    category: "minor",
    genres: ["Ballad", "Game", "Jazz"],
    moods: ["dark", "tense", "resolved"],
    useCases: ["ending", "turnaround"],
    complexity: 2,
    description: "Compact minor predominant to dominant cadence.",
  }),
  preset({
    id: "emotional-minor",
    name: "Emotional Minor",
    roman: ["i", "bIII", "bVI", "V"],
    mode: "minor",
    category: "minor",
    genres: ["J-Pop", "Anime", "Ballad"],
    moods: ["emotional", "dark", "dramatic"],
    useCases: ["chorus", "bridge"],
    complexity: 2,
    description: "Relative-major warmth with a dramatic V return.",
  }),
  preset({
    id: "phrygian-color",
    name: "Phrygian Color",
    roman: ["i", "bII", "bVII", "i"],
    mode: "minor",
    category: "minor",
    genres: ["Game", "Rock", "Modal"],
    moods: ["dark", "tense", "dramatic"],
    useCases: ["intro", "bridge"],
    complexity: 3,
    description: "bII modal pull with a grounded return to i.",
  }),
  preset({
    id: "minor-modal-loop",
    name: "Minor Modal Loop",
    roman: ["i", "bVII", "IV", "i"],
    mode: "minor",
    category: "minor",
    genres: ["Rock", "Game", "Modal"],
    moods: ["dark", "open", "loopable"],
    useCases: ["loop", "verse"],
    complexity: 3,
    description: "Minor-modal loop with a bright IV color.",
  }),
  preset({
    id: "minor-story",
    name: "Minor Story",
    roman: ["i", "iv", "bVII", "bIII"],
    mode: "minor",
    category: "minor",
    genres: ["Anime", "Game", "Pop"],
    moods: ["emotional", "dark", "dramatic"],
    useCases: ["verse", "pre-chorus"],
    complexity: 2,
    description: "Minor subdominant opens into a relative-major landing.",
  }),
  preset({
    id: "minor-pop-loop",
    name: "Minor Pop Loop",
    roman: ["i", "iv", "bVI", "V"],
    mode: "minor",
    category: "minor",
    genres: ["Pop", "Anime", "Ballad"],
    moods: ["emotional", "tense", "dark"],
    useCases: ["chorus", "loop"],
    complexity: 2,
    description: "Minor pop loop with a strong dominant reset.",
  }),
  preset({
    id: "dark-cadence",
    name: "Dark Cadence",
    roman: ["i", "bVI", "V", "i"],
    mode: "minor",
    category: "minor",
    genres: ["Game", "Ballad"],
    moods: ["dark", "tense", "resolved"],
    useCases: ["ending", "bridge"],
    complexity: 2,
    description: "Aeolian color into a strong harmonic-minor close.",
  }),
  preset({
    id: "minor-run",
    name: "Minor Run",
    roman: ["i", "bVII", "bVI", "bVII"],
    mode: "minor",
    category: "minor",
    genres: ["Rock", "EDM", "Game"],
    moods: ["dark", "loopable", "tense"],
    useCases: ["loop", "intro"],
    complexity: 2,
    description: "Aeolian rock descent with a returning bVII push.",
  }),
  preset({
    id: "minor-flight",
    name: "Minor Flight",
    roman: ["i", "bIII", "bVII", "iv"],
    mode: "minor",
    category: "minor",
    genres: ["Anime", "Game", "Pop"],
    moods: ["dramatic", "emotional", "dark"],
    useCases: ["pre-chorus", "bridge"],
    complexity: 2,
    description: "Relative-major lift that falls back into minor iv.",
  }),
  preset({
    id: "minor-edm",
    name: "Minor EDM",
    roman: ["i", "bVI", "bIII", "bVII"],
    mode: "minor",
    category: "minor",
    genres: ["EDM", "Game", "Pop"],
    moods: ["dramatic", "loopable", "dark"],
    useCases: ["drop", "loop", "chorus"],
    complexity: 2,
    description: "A broad minor loop that works well as a dance seed.",
  }),
  preset({
    id: "minor-ballad",
    name: "Minor Ballad",
    roman: ["i", "iv", "bVI", "bVII"],
    mode: "minor",
    category: "minor",
    genres: ["Ballad", "J-Pop", "Anime"],
    moods: ["emotional", "dark", "nostalgic"],
    useCases: ["verse", "chorus"],
    complexity: 2,
    description: "Minor subdominant and flat-side color without hard cadence.",
  }),
  preset({
    id: "minor-resolve",
    name: "Minor Resolve",
    roman: ["i", "bVI", "iiø7", "V7"],
    mode: "minor",
    category: "minor",
    genres: ["Jazz", "Ballad", "Game"],
    moods: ["dark", "tense", "smooth"],
    useCases: ["pre-chorus", "turnaround"],
    complexity: 4,
    description: "Minor tonic color into a strong ii-V dominant setup.",
  }),
  preset({
    id: "major-ii-v-i",
    name: "Major ii-V-I",
    roman: ["ii7", "V7", "Imaj7"],
    mode: "major",
    category: "ii-V",
    genres: ["Jazz", "City Pop", "R&B"],
    moods: ["smooth", "resolved", "stable"],
    useCases: ["ending", "turnaround"],
    complexity: 3,
    description: "Core functional cadence for jazz, city pop, and R&B.",
  }),
  preset({
    id: "minor-ii-v-i",
    name: "Minor ii-V-i",
    roman: ["iiø7", "V7", "i"],
    mode: "minor",
    category: "ii-V",
    genres: ["Jazz", "Ballad"],
    moods: ["dark", "smooth", "resolved"],
    useCases: ["ending", "turnaround"],
    complexity: 4,
    description: "Minor cadence with half-diminished predominant.",
  }),
  preset({
    id: "rhythm-a",
    name: "Rhythm Changes A",
    roman: ["Imaj7", "VI7", "ii7", "V7"],
    mode: "major",
    category: "ii-V",
    genres: ["Jazz", "City Pop"],
    moods: ["smooth", "nostalgic", "loopable"],
    useCases: ["turnaround", "loop"],
    complexity: 4,
    description: "Dominant color inside a compact jazz turnaround.",
  }),
  preset({
    id: "three-six-two-five",
    name: "iii-VI-ii-V",
    roman: ["iii7", "VI7", "ii7", "V7"],
    mode: "major",
    category: "ii-V",
    genres: ["Jazz", "City Pop", "R&B"],
    moods: ["smooth", "floating", "loopable"],
    useCases: ["verse", "turnaround"],
    complexity: 4,
    description: "Classic chain of dominants returning toward I.",
  }),
  preset({
    id: "city-night",
    name: "City Night",
    roman: ["ii7", "V7", "iii7", "vi7"],
    mode: "major",
    category: "ii-V",
    genres: ["City Pop", "J-Pop", "Jazz"],
    moods: ["smooth", "floating", "nostalgic"],
    useCases: ["intro", "verse", "loop"],
    complexity: 4,
    description: "Cadence fragment that delays tonic resolution.",
  }),
  preset({
    id: "backdoor-cadence",
    name: "Backdoor Cadence",
    roman: ["iv7", "bVII7", "Imaj7"],
    mode: "major",
    category: "ii-V",
    genres: ["Jazz", "R&B", "City Pop"],
    moods: ["smooth", "emotional", "resolved"],
    useCases: ["ending", "turnaround"],
    complexity: 4,
    description: "Borrowed minor subdominant into a backdoor resolution.",
  }),
  preset({
    id: "neo-soul-color",
    name: "Neo Soul Color",
    roman: ["Imaj7", "VII7", "iii7", "vi7"],
    mode: "major",
    category: "ii-V",
    genres: ["R&B", "Jazz", "City Pop"],
    moods: ["smooth", "floating", "tense"],
    useCases: ["verse", "loop"],
    complexity: 5,
    description: "Outside dominant color for a richer tonic-area loop.",
  }),
  preset({
    id: "subdominant-ii-v",
    name: "Subdominant ii-V",
    roman: ["V/IV", "IVmaj7", "ii7", "V7"],
    mode: "major",
    category: "ii-V",
    genres: ["Jazz", "City Pop"],
    moods: ["smooth", "dramatic", "resolved"],
    useCases: ["bridge", "turnaround"],
    complexity: 5,
    description: "Secondary dominant points to IV before the main cadence.",
  }),
  preset({
    id: "minor-chain",
    name: "Minor Chain",
    roman: ["i7", "VI7", "iiø7", "V7"],
    mode: "minor",
    category: "ii-V",
    genres: ["Jazz", "R&B"],
    moods: ["dark", "smooth", "tense"],
    useCases: ["verse", "turnaround"],
    complexity: 5,
    description: "Minor tonic color with a dominant-heavy cadence chain.",
  }),
  preset({
    id: "jazz-pop-loop",
    name: "Jazz Pop Loop",
    roman: ["Imaj7", "bVII7", "iii7", "VI7"],
    mode: "major",
    category: "ii-V",
    genres: ["City Pop", "Jazz", "R&B"],
    moods: ["smooth", "nostalgic", "tense"],
    useCases: ["intro", "verse"],
    complexity: 5,
    description: "Backdoor color leading into a iii-VI turnaround fragment.",
  }),
  preset({
    id: "soul-two-five",
    name: "Soul ii-V",
    roman: ["IVmaj7", "iv7", "iii7", "VI7"],
    mode: "major",
    category: "ii-V",
    genres: ["R&B", "Jazz", "City Pop"],
    moods: ["smooth", "emotional", "floating"],
    useCases: ["verse", "bridge"],
    complexity: 5,
    description: "Borrowed iv and III/VI colors for a soulful loop.",
  }),
  preset({
    id: "perfect-cadence",
    name: "Perfect Cadence",
    roman: ["ii", "V", "I"],
    mode: "major",
    category: "turnaround",
    genres: ["Pop", "Jazz", "Ballad"],
    moods: ["resolved", "stable"],
    useCases: ["ending", "turnaround"],
    complexity: 1,
    description: "Plain predominant to dominant to tonic.",
  }),
  preset({
    id: "plagal-cadence",
    name: "Plagal Cadence",
    roman: ["IV", "I"],
    mode: "major",
    category: "turnaround",
    genres: ["Pop", "Ballad", "Rock"],
    moods: ["resolved", "stable", "emotional"],
    useCases: ["ending"],
    complexity: 1,
    description: "Subdominant return with an amen-cadence feel.",
  }),
  preset({
    id: "minor-plagal",
    name: "Minor Plagal",
    roman: ["iv", "I"],
    mode: "major",
    category: "turnaround",
    genres: ["R&B", "Ballad", "J-Pop"],
    moods: ["emotional", "smooth", "resolved"],
    useCases: ["ending", "bridge"],
    complexity: 2,
    description: "Borrowed iv resolving softly into major tonic.",
  }),
  preset({
    id: "deceptive-cadence",
    name: "Deceptive Cadence",
    roman: ["V", "vi"],
    mode: "major",
    category: "turnaround",
    genres: ["Pop", "J-Pop", "Ballad"],
    moods: ["emotional", "tense", "loopable"],
    useCases: ["bridge", "turnaround"],
    complexity: 1,
    description: "Dominant avoids tonic and lands on relative minor.",
  }),
  preset({
    id: "backdoor",
    name: "Backdoor",
    roman: ["iv", "bVII", "I"],
    mode: "major",
    category: "turnaround",
    genres: ["Jazz", "R&B", "City Pop"],
    moods: ["smooth", "emotional", "resolved"],
    useCases: ["ending", "turnaround"],
    complexity: 3,
    description: "Borrowed subdominant into modal bVII and I.",
  }),
  preset({
    id: "secondary-push",
    name: "Secondary Push",
    roman: ["I", "V/vi", "vi"],
    mode: "major",
    category: "turnaround",
    genres: ["Pop", "J-Pop", "Anime"],
    moods: ["tense", "emotional", "loopable"],
    useCases: ["turnaround", "loop"],
    complexity: 3,
    description: "Tonic into secondary dominant targeting relative minor.",
  }),
  preset({
    id: "extended-turnaround",
    name: "Extended Turnaround",
    roman: ["I", "VI7", "ii7", "V7"],
    mode: "major",
    category: "turnaround",
    genres: ["Jazz", "City Pop"],
    moods: ["smooth", "nostalgic", "loopable"],
    useCases: ["turnaround", "loop"],
    complexity: 4,
    description: "Secondary dominant into a jazz ii-V turnaround.",
  }),
  preset({
    id: "pop-ending",
    name: "Pop Ending",
    roman: ["IV", "V", "I"],
    mode: "major",
    category: "turnaround",
    genres: ["Pop", "J-Pop", "Anime"],
    moods: ["bright", "resolved", "dramatic"],
    useCases: ["ending", "chorus"],
    complexity: 1,
    description: "Compact IV-V-I close for a direct ending.",
  }),
  preset({
    id: "minor-ending",
    name: "Minor Ending",
    roman: ["iv", "V7", "i"],
    mode: "minor",
    category: "turnaround",
    genres: ["Ballad", "Game", "Jazz"],
    moods: ["dark", "resolved", "tense"],
    useCases: ["ending"],
    complexity: 2,
    description: "Minor subdominant into a strong V7-i close.",
  }),
  preset({
    id: "loop-reset",
    name: "Loop Reset",
    roman: ["I", "vi", "ii7", "V7"],
    mode: "major",
    category: "turnaround",
    genres: ["Pop", "Jazz", "City Pop"],
    moods: ["smooth", "stable", "loopable"],
    useCases: ["turnaround", "loop"],
    complexity: 3,
    description: "A compact reset that makes the loop feel intentional.",
  }),
  preset({
    id: "emotional-ending",
    name: "Emotional Ending",
    roman: ["vi", "IV", "V", "I"],
    mode: "major",
    category: "turnaround",
    genres: ["J-Pop", "Anime", "Ballad"],
    moods: ["emotional", "resolved", "dramatic"],
    useCases: ["ending", "chorus"],
    complexity: 2,
    description: "Relative-minor start that resolves with IV-V-I weight.",
  }),
  preset({
    id: "half-cadence",
    name: "Half Cadence",
    roman: ["I", "IV", "V"],
    mode: "major",
    category: "turnaround",
    genres: ["Pop", "Rock", "Ballad"],
    moods: ["tense", "stable", "open"],
    useCases: ["pre-chorus", "bridge"],
    complexity: 1,
    description: "Stops on V to keep the next section waiting.",
  }),
  preset({
    id: "mixolydian-rock",
    name: "Mixolydian Rock",
    roman: ["I", "bVII", "IV", "I"],
    mode: "major",
    category: "modal",
    genres: ["Rock", "Game", "Pop"],
    moods: ["open", "bright", "loopable"],
    useCases: ["verse", "loop"],
    complexity: 2,
    description: "Modal rock color centered around bVII and IV.",
  }),
  preset({
    id: "borrowed-lift",
    name: "Borrowed Lift",
    roman: ["I", "bVI", "bVII", "I"],
    mode: "major",
    category: "modal",
    genres: ["Rock", "Game", "Anime"],
    moods: ["dramatic", "dark", "resolved"],
    useCases: ["bridge", "chorus"],
    complexity: 3,
    description: "Flat-side borrowed lift that resolves back to I.",
  }),
  preset({
    id: "dream-pop",
    name: "Dream Pop",
    roman: ["Imaj7", "bVIImaj7", "IVmaj7", "Imaj7"],
    mode: "major",
    category: "modal",
    genres: ["Pop", "R&B", "City Pop"],
    moods: ["floating", "smooth", "nostalgic"],
    useCases: ["intro", "verse", "loop"],
    complexity: 4,
    description: "Major-seventh modal wash with a soft return home.",
  }),
  preset({
    id: "dark-major",
    name: "Dark Major",
    roman: ["I", "bIII", "bVI", "bVII"],
    mode: "major",
    category: "modal",
    genres: ["Rock", "Game", "Anime"],
    moods: ["dark", "dramatic", "tense"],
    useCases: ["bridge", "intro"],
    complexity: 3,
    description: "Major tonic with parallel-minor borrowed color.",
  }),
  preset({
    id: "lydian-hint",
    name: "Lydian Hint",
    roman: ["I", "II", "IV", "I"],
    mode: "major",
    category: "modal",
    genres: ["Game", "Pop", "Anime"],
    moods: ["bright", "floating", "open"],
    useCases: ["intro", "bridge"],
    complexity: 3,
    description: "Raised-II color for a practical Lydian-flavored lift.",
  }),
  preset({
    id: "phrygian-pull",
    name: "Phrygian Pull",
    roman: ["i", "bII", "i"],
    mode: "minor",
    category: "modal",
    genres: ["Game", "Rock"],
    moods: ["dark", "tense", "dramatic"],
    useCases: ["intro", "bridge"],
    complexity: 2,
    description: "bII tension pulling directly back to minor tonic.",
  }),
  preset({
    id: "modal-loop",
    name: "Modal Loop",
    roman: ["i", "bVII", "IV", "i"],
    mode: "minor",
    category: "modal",
    genres: ["Rock", "Game", "Modal"],
    moods: ["open", "dark", "loopable"],
    useCases: ["loop", "verse"],
    complexity: 3,
    description: "Minor-modal loop with a bright IV color.",
  }),
  preset({
    id: "flat-side-return",
    name: "Flat-Side Return",
    roman: ["bVI", "bVII", "I"],
    mode: "major",
    category: "modal",
    genres: ["Rock", "Anime", "Game"],
    moods: ["dramatic", "resolved", "bright"],
    useCases: ["ending", "bridge"],
    complexity: 3,
    description: "Flat-six to flat-seven creates a big modal return to I.",
  }),
  preset({
    id: "minor-borrow",
    name: "Minor Borrow",
    roman: ["I", "iv", "I"],
    mode: "major",
    category: "borrowed",
    genres: ["R&B", "Ballad", "J-Pop"],
    moods: ["emotional", "smooth", "nostalgic"],
    useCases: ["bridge", "ending"],
    complexity: 2,
    description: "Major tonic touched by borrowed minor iv.",
  }),
  preset({
    id: "gospel-walk",
    name: "Gospel Walk",
    roman: ["I", "iii", "IV", "iv"],
    mode: "major",
    category: "borrowed",
    genres: ["R&B", "Gospel", "Ballad"],
    moods: ["emotional", "smooth", "resolved"],
    useCases: ["verse", "ending"],
    complexity: 3,
    description: "Tonic-area lift into a borrowed iv color.",
  }),
  preset({
    id: "borrowed-ballad",
    name: "Borrowed Ballad",
    roman: ["I", "bIII", "IV", "iv"],
    mode: "major",
    category: "borrowed",
    genres: ["Ballad", "J-Pop", "R&B"],
    moods: ["emotional", "nostalgic", "dramatic"],
    useCases: ["bridge", "ending"],
    complexity: 4,
    description: "Parallel-minor color rises into IV and softens through iv.",
  }),
  preset({
    id: "borrowed-drama",
    name: "Borrowed Drama",
    roman: ["I", "bVI", "iv", "I"],
    mode: "major",
    category: "borrowed",
    genres: ["Anime", "Game", "Ballad"],
    moods: ["dramatic", "emotional", "resolved"],
    useCases: ["bridge", "ending"],
    complexity: 4,
    description: "Flat-six and borrowed iv make a compact dramatic turn.",
  }),
  preset({
    id: "borrowed-pop-loop",
    name: "Borrowed Pop Loop",
    roman: ["I", "bVII", "vi", "IV"],
    mode: "major",
    category: "borrowed",
    genres: ["Pop", "Rock", "Anime"],
    moods: ["bright", "dramatic", "loopable"],
    useCases: ["chorus", "loop"],
    complexity: 3,
    description: "A familiar pop loop colored by modal bVII.",
  }),
  preset({
    id: "borrowed-ending",
    name: "Borrowed Ending",
    roman: ["IV", "iv", "bVII", "I"],
    mode: "major",
    category: "borrowed",
    genres: ["R&B", "City Pop", "Ballad"],
    moods: ["smooth", "emotional", "resolved"],
    useCases: ["ending", "turnaround"],
    complexity: 4,
    description: "IV-iv softens into bVII before resolving home.",
  }),
  preset({
    id: "game-adventure",
    name: "Game Adventure",
    roman: ["I", "bVII", "IV", "V"],
    mode: "major",
    category: "other",
    genres: ["Game", "Rock"],
    moods: ["bright", "dramatic", "open"],
    useCases: ["intro", "loop"],
    complexity: 3,
    description: "Modal rock color that still points to a dominant reset.",
  }),
  preset({
    id: "edm-rise",
    name: "EDM Rise",
    roman: ["vi", "IV", "I", "V"],
    mode: "major",
    category: "other",
    genres: ["EDM", "Pop", "J-Pop"],
    moods: ["bright", "emotional", "loopable"],
    useCases: ["chorus", "loop"],
    complexity: 1,
    description: "High-energy loop for drops and big repeated hooks.",
  }),
  preset({
    id: "game-town",
    name: "Game Town",
    roman: ["I", "IVmaj7", "ii7", "V"],
    mode: "major",
    category: "other",
    genres: ["Game", "Pop"],
    moods: ["bright", "stable", "floating"],
    useCases: ["intro", "loop"],
    complexity: 3,
    description: "Friendly major color with a soft jazz-pop cadence.",
  }),
  preset({
    id: "anime-bridge",
    name: "Anime Bridge",
    roman: ["bVI", "bVII", "V/vi", "vi"],
    mode: "major",
    category: "other",
    genres: ["Anime", "J-Pop", "Game"],
    moods: ["dramatic", "tense", "emotional"],
    useCases: ["bridge", "pre-chorus"],
    complexity: 4,
    description: "Flat-side drama into a secondary dominant targeting vi.",
  }),
];

function uniqueSorted(values: string[]) {
  return Array.from(new Set(values)).sort((a, b) => a.localeCompare(b));
}

export const PRESET_CATEGORIES: ProgressionPresetCategory[] = [
  "I-start",
  "IV-start",
  "vi-start",
  "minor",
  "ii-V",
  "turnaround",
  "modal",
  "borrowed",
  "other",
];

export const PRESET_GENRES = uniqueSorted(
  STARTER_PRESETS.flatMap((preset) => preset.genres)
);

export const PRESET_MOODS = uniqueSorted(
  STARTER_PRESETS.flatMap((preset) => preset.moods)
);

export const PRESET_USE_CASES = uniqueSorted(
  STARTER_PRESETS.flatMap((preset) => preset.useCases)
);

export const PRESET_COMPLEXITIES = ["1", "2", "3", "4", "5"] as const;

export function progressionPresetRomanLabel(preset: ProgressionPreset) {
  return preset.roman.join(" - ");
}

export function progressionPresetToChords(
  preset: ProgressionPreset,
  params: { key: string; mode: KeyMode }
) {
  const cacheKey = `${preset.id}|${params.key}|${params.mode}|${preset.roman.join(" ")}`;
  const cached = presetChordCache.get(cacheKey);
  if (cached) return cached;

  const chords = preset.roman.map((roman) => romanCandidateToChord(roman, params));
  presetChordCache.set(cacheKey, chords);
  if (presetChordCache.size > PRESET_CHORD_CACHE_LIMIT) {
    const oldest = presetChordCache.keys().next().value;
    if (oldest !== undefined) presetChordCache.delete(oldest);
  }
  return chords;
}

function selectedValue(value?: string) {
  return value && value !== "All" ? value.toLowerCase() : "";
}

function includesSelected(values: string[], selected?: string) {
  const normalized = selectedValue(selected);
  if (!normalized) return true;
  return values.some((value) => value.toLowerCase() === normalized);
}

export function filterProgressionPresets(
  presets: ProgressionPreset[],
  filter: PresetFilter,
  options: {
    convertedChords?: (preset: ProgressionPreset) => string[];
  } = {}
) {
  const category = selectedValue(filter.category);
  const complexity =
    filter.complexity && filter.complexity !== "All"
      ? Number(filter.complexity)
      : 0;
  const query = filter.search?.trim().toLowerCase() ?? "";

  return presets.filter((preset) => {
    if (category && preset.category.toLowerCase() !== category) return false;
    if (!includesSelected(preset.genres, filter.genre)) return false;
    if (!includesSelected(preset.moods, filter.mood)) return false;
    if (!includesSelected(preset.useCases, filter.useCase)) return false;
    if (complexity && preset.complexity !== complexity) return false;
    if (!query) return true;

    const references =
      preset.referenceSongs?.flatMap((ref) => [
        ref.title,
        ref.artist ?? "",
        ref.section ?? "",
        ref.note ?? "",
      ]) ?? [];
    const convertedChords = options.convertedChords?.(preset) ?? [];
    const haystack = [
      preset.name,
      progressionPresetRomanLabel(preset),
      convertedChords.join(" "),
      preset.description,
      preset.commonUse ?? "",
      preset.mode,
      preset.category,
      ...preset.genres,
      ...preset.moods,
      ...preset.useCases,
      ...(preset.vibeExamples ?? []),
      ...references,
    ]
      .join(" ")
      .toLowerCase();
    return haystack.includes(query);
  });
}
